























.build/uno-dd8692bf/Servo/Servo.o : /home/robotto/Hack/arduino-1.0.6/libraries/Servo/Servo.cpp
	@echo [93mServo/Servo.cpp[0m
	@mkdir -p .build/uno-dd8692bf/Servo
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/robotto/Hack/arduino-1.0.6/libraries/Servo/Servo.cpp
include .build/uno-dd8692bf/Servo/Servo.d



.build/uno-dd8692bf/Servo/libServo.a : .build/uno-dd8692bf/Servo/Servo.o
	@echo [92mLinking libServo.a[0m
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build/uno-dd8692bf/arduino/avr-libc/malloc.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc/malloc.c
	@echo [93marduino/avr-libc/malloc.c[0m
	@mkdir -p .build/uno-dd8692bf/arduino/avr-libc
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc/malloc.c
include .build/uno-dd8692bf/arduino/avr-libc/malloc.d

.build/uno-dd8692bf/arduino/avr-libc/realloc.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc/realloc.c
	@echo [93marduino/avr-libc/realloc.c[0m
	@mkdir -p .build/uno-dd8692bf/arduino/avr-libc
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc/realloc.c
include .build/uno-dd8692bf/arduino/avr-libc/realloc.d

.build/uno-dd8692bf/arduino/WInterrupts.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/WInterrupts.c
include .build/uno-dd8692bf/arduino/WInterrupts.d

.build/uno-dd8692bf/arduino/wiring.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/wiring.c
include .build/uno-dd8692bf/arduino/wiring.d

.build/uno-dd8692bf/arduino/wiring_shift.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/wiring_shift.c
include .build/uno-dd8692bf/arduino/wiring_shift.d

.build/uno-dd8692bf/arduino/wiring_pulse.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/wiring_pulse.c
include .build/uno-dd8692bf/arduino/wiring_pulse.d

.build/uno-dd8692bf/arduino/wiring_analog.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/wiring_analog.c
include .build/uno-dd8692bf/arduino/wiring_analog.d

.build/uno-dd8692bf/arduino/wiring_digital.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/wiring_digital.c
include .build/uno-dd8692bf/arduino/wiring_digital.d






.build/uno-dd8692bf/arduino/CDC.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/CDC.cpp
include .build/uno-dd8692bf/arduino/CDC.d

.build/uno-dd8692bf/arduino/main.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/main.cpp
include .build/uno-dd8692bf/arduino/main.d

.build/uno-dd8692bf/arduino/new.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/new.cpp
include .build/uno-dd8692bf/arduino/new.d

.build/uno-dd8692bf/arduino/WString.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/WString.cpp
include .build/uno-dd8692bf/arduino/WString.d

.build/uno-dd8692bf/arduino/IPAddress.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/IPAddress.cpp
include .build/uno-dd8692bf/arduino/IPAddress.d

.build/uno-dd8692bf/arduino/Print.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/Print.cpp
include .build/uno-dd8692bf/arduino/Print.d

.build/uno-dd8692bf/arduino/HID.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/HID.cpp
include .build/uno-dd8692bf/arduino/HID.d

.build/uno-dd8692bf/arduino/WMath.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/WMath.cpp
include .build/uno-dd8692bf/arduino/WMath.d

.build/uno-dd8692bf/arduino/Tone.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/Tone.cpp
include .build/uno-dd8692bf/arduino/Tone.d

.build/uno-dd8692bf/arduino/HardwareSerial.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build/uno-dd8692bf/arduino/HardwareSerial.d

.build/uno-dd8692bf/arduino/USBCore.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/USBCore.cpp
include .build/uno-dd8692bf/arduino/USBCore.d

.build/uno-dd8692bf/arduino/Stream.o : /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build/uno-dd8692bf/arduino
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/Stream.cpp
include .build/uno-dd8692bf/arduino/Stream.d



.build/uno-dd8692bf/arduino/libarduino.a : .build/uno-dd8692bf/arduino/avr-libc/malloc.o .build/uno-dd8692bf/arduino/avr-libc/realloc.o .build/uno-dd8692bf/arduino/WInterrupts.o .build/uno-dd8692bf/arduino/wiring.o .build/uno-dd8692bf/arduino/wiring_shift.o .build/uno-dd8692bf/arduino/wiring_pulse.o .build/uno-dd8692bf/arduino/wiring_analog.o .build/uno-dd8692bf/arduino/wiring_digital.o .build/uno-dd8692bf/arduino/CDC.o .build/uno-dd8692bf/arduino/main.o .build/uno-dd8692bf/arduino/new.o .build/uno-dd8692bf/arduino/WString.o .build/uno-dd8692bf/arduino/IPAddress.o .build/uno-dd8692bf/arduino/Print.o .build/uno-dd8692bf/arduino/HID.o .build/uno-dd8692bf/arduino/WMath.o .build/uno-dd8692bf/arduino/Tone.o .build/uno-dd8692bf/arduino/HardwareSerial.o .build/uno-dd8692bf/arduino/USBCore.o .build/uno-dd8692bf/arduino/Stream.o
	@echo [92mLinking libarduino.a[0m
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build/uno-dd8692bf/src/volume.o : .build/uno-dd8692bf/src/volume.cpp
	@echo [93msrc/volume.cpp[0m
	@mkdir -p .build/uno-dd8692bf/src
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=106 -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/variants/standard -I/home/robotto/Hack/arduino-1.0.6/libraries/Servo -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino -I/home/robotto/Hack/arduino-1.0.6/hardware/arduino/cores/arduino/avr-libc -fno-exceptions -iquote src  -o $@ -c .build/uno-dd8692bf/src/volume.cpp
include .build/uno-dd8692bf/src/volume.d







.build/uno-dd8692bf/firmware.elf : .build/uno-dd8692bf/src/volume.o .build/uno-dd8692bf/Servo/libServo.a .build/uno-dd8692bf/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build/uno-dd8692bf/firmware.hex : .build/uno-dd8692bf/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/home/robotto/Hack/arduino-1.0.6/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/uno-dd8692bf/src/dependencies.d .build/uno-dd8692bf/arduino/dependencies.d .build/uno-dd8692bf/Servo/dependencies.d

all : .build/uno-dd8692bf/firmware.hex
	@true

